/**
 * This file is autogenerated by Scaffold-Stark.
 * You should not edit it manually or your changes might be overwritten.
 */
import {
  universalEthAddress,
  universalStrkAddress,
  universalClassHash,
  universalAbi,
} from "./Constants";

const preDeployedContracts = {
  devnet: {
    Eth: {
      address: universalEthAddress,
      abi: universalAbi,
      classHash: universalClassHash,
    },
    Strk: {
      address: universalStrkAddress,
      abi: universalAbi,
      classHash: universalClassHash,
    },
  },
  sepolia: {
    Eth: {
      address: universalEthAddress,
      abi: universalAbi,
      classHash:
        "0x07f3777c99f3700505ea966676aac4a0d692c2a9f5e667f4c606b51ca1dd3420",
    },
    Strk: {
      address: universalStrkAddress,
      abi: universalAbi,
      classHash:
        "0x04ad3c1dc8413453db314497945b6903e1c766495a1e60492d44da9c2a986e4b",
    },
  },
  mainnet: {
    Eth: {
      address: universalEthAddress,
      abi: universalAbi,
      classHash: universalClassHash,
    },
    Strk: {
      address: universalStrkAddress,
      abi: universalAbi,
      classHash: universalClassHash,
    },
  },
} as const;

export default preDeployedContracts;
